create table his_error_operation_record (
    id bigint generated by default as identity primary key,
    error_id bigint not null unique,
    status varchar(30) not null,
    memo text not null,
    last_analysis_summary varchar(1000) not null,
    last_analysis_answer text not null,
    analyzed_at timestamptz,
    updated_at timestamptz not null
);

create index idx_his_error_operation_record_status on his_error_operation_record (status);
create index idx_his_error_operation_record_updated_at on his_error_operation_record (updated_at);
