create table source_system (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(100) not null,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table customers (
    id bigint generated by default as identity primary key,
    customer_no varchar(50) not null unique,
    customer_name varchar(100) not null,
    customer_phone varchar(30),
    source_system_id bigint not null references source_system (id),
    created_at timestamptz not null
);

create index idx_customers_source_system_id on customers (source_system_id);
create index idx_customers_created_at on customers (created_at);

create table orders (
    id bigint generated by default as identity primary key,
    order_no varchar(50) not null unique,
    customer_id bigint not null references customers (id),
    source_system_id bigint not null references source_system (id),
    order_status varchar(30) not null,
    order_amount numeric(15, 2) not null,
    ordered_at timestamptz not null,
    ingested_at timestamptz not null
);

create index idx_orders_customer_id on orders (customer_id);
create index idx_orders_source_system_id on orders (source_system_id);
create index idx_orders_ordered_at on orders (ordered_at);
create index idx_orders_ingested_at on orders (ingested_at);

create table payments (
    id bigint generated by default as identity primary key,
    payment_id varchar(80) not null,
    order_id bigint not null references orders (id),
    source_system_id bigint not null references source_system (id),
    payment_status varchar(30) not null,
    amount numeric(15, 2) not null,
    paid_at timestamptz not null
);

create index idx_payments_payment_id on payments (payment_id);
create index idx_payments_order_id on payments (order_id);
create index idx_payments_source_system_id on payments (source_system_id);
create index idx_payments_paid_at on payments (paid_at);

create table data_ingestion_log (
    id bigint generated by default as identity primary key,
    source_system_id bigint not null references source_system (id),
    target_table varchar(50) not null,
    batch_date date not null,
    received_count integer not null,
    success_count integer not null,
    failed_count integer not null,
    status varchar(30) not null,
    started_at timestamptz not null,
    ended_at timestamptz
);

create index idx_data_ingestion_log_source_system_id on data_ingestion_log (source_system_id);
create index idx_data_ingestion_log_target_batch on data_ingestion_log (target_table, batch_date);
