create table detection_rule (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    target_table varchar(50) not null,
    metric_type varchar(50) not null,
    threshold_type varchar(50) not null,
    threshold_value numeric(12, 4) not null,
    enabled boolean not null default true,
    created_at timestamptz not null default now()
);

create table incident (
    id bigint generated by default as identity primary key,
    incident_no varchar(50) not null unique,
    detection_rule_id bigint references detection_rule (id),
    severity varchar(30) not null,
    status varchar(30) not null,
    target_table varchar(50) not null,
    anomaly_type varchar(50) not null,
    summary varchar(300) not null,
    detected_at timestamptz not null,
    resolved_at timestamptz
);

create index idx_incident_status on incident (status);
create index idx_incident_severity on incident (severity);
create index idx_incident_detected_at on incident (detected_at);
create index idx_incident_target_anomaly on incident (target_table, anomaly_type);

create table incident_metric_snapshot (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references incident (id) on delete cascade,
    metric_name varchar(100) not null,
    baseline_value numeric(15, 4) not null,
    current_value numeric(15, 4) not null,
    change_rate numeric(12, 4),
    measured_at timestamptz not null
);

create index idx_incident_metric_snapshot_incident_id on incident_metric_snapshot (incident_id);
