create table scenario (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    scenario_type varchar(60) not null,
    target_source_code varchar(50) not null,
    target_date date not null,
    affected_rows integer not null,
    expected_incident_type varchar(60) not null,
    expected_cause text not null,
    injected_at timestamptz not null
);

create index idx_scenario_type on scenario (scenario_type);
create index idx_scenario_target on scenario (target_source_code, target_date);
