create table incident_analysis (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references incident (id) on delete cascade,
    summary varchar(1000) not null,
    impact_scope varchar(1000) not null,
    suspected_causes_json text not null,
    verification_sql_json text not null,
    additional_checks_json text not null,
    mock boolean not null,
    analyzed_at timestamptz not null
);

create index idx_incident_analysis_incident_id on incident_analysis (incident_id);
create index idx_incident_analysis_analyzed_at on incident_analysis (analyzed_at);
