create table incident_report (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references incident (id) on delete cascade,
    incident_analysis_id bigint not null references incident_analysis (id) on delete cascade,
    report_type varchar(30) not null,
    title varchar(200) not null,
    content text not null,
    generated_at timestamptz not null
);

create index idx_incident_report_incident_id on incident_report (incident_id);
create index idx_incident_report_analysis_id on incident_report (incident_analysis_id);
create index idx_incident_report_type_generated_at on incident_report (report_type, generated_at);
