create table analysis_job (
    id bigint generated by default as identity primary key,
    job_id varchar(80) not null unique,
    incident_id bigint not null references incident (id),
    status varchar(30) not null,
    requested_by varchar(120),
    request_text varchar(1000),
    slack_channel_id varchar(120),
    slack_thread_ts varchar(120),
    slack_response_url varchar(1000),
    error_message varchar(2000),
    created_at timestamptz not null,
    started_at timestamptz,
    completed_at timestamptz
);

create index idx_analysis_job_incident_id on analysis_job (incident_id);
create index idx_analysis_job_status_created_at on analysis_job (status, created_at);
