spring:
  application:
    name: OpsLens
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/opslens}
    username: ${SPRING_DATASOURCE_USERNAME:opslens}
    password: ${SPRING_DATASOURCE_PASSWORD:opslens}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
